### ISSUE TITLE
Requirements(Dependencies) 부분에 파이썬이용과 파이썬 버젼을 명시적으로 적어 주는 것은 어떨까요?

### ISSUE THREAD

**Issue by novelview9** [jupiny/ndic#1]
보통은 다 적던데...

**Comment by jupiny** [comment]
아 그런가요?
제가 다른 파이썬 패키지들 보면서 한 번 알아보겠습니다.

**Comment by jupiny** [comment]
@novelview9 님, 지적해주신 대로 이용가능한 파이썬 버젼들을 적어두었습니다. 

https://github.com/jupiny/ndic#requirements

Travis 테스트에서 통과함을 다 확인하였구요.
3.2 버젼에서 계속 테스트가 에러 떠서 한참 애를 먹었는데, 알아보니 [Requests](http://docs.python-requests.org/en/master/)에서 3.2 버젼을 지원하지 않더군요..하하;;

http://docs.python-requests.org/en/master/#supported-features

그래서 쿨하게 3.2 버젼은 포기하였습니다.

**Comment by novelview9** [comment]
쿨함에 337 박수를 드립니다.
짝짝짝 짝짝짝 짝짝짝짝짝짝짝
