### ISSUE TITLE
Words with multiple definitions

### ISSUE THREAD

**Issue by jonathanmbinder** [jupiny/ndic#2]
When a word with multiple definitions such as "말" is entered, only the first definition is returned.

**Comment by jupiny** [comment]
Thank you for living the issue. I'll check this problem later!

**Comment by Ninjaman494** [comment]
I just checked tried to this out and I got multiple definitions: 
`ndic.search('말')`
`'(언어) word, language, speech, (literary) tongue'`

I guess it's been fixed since this issue was opened, it should probably be closed.

**Comment by jupiny** [comment]
@Ninjaman494 I've forgotten this issue. The issue has not been fixed yet... 
For example, "말", has another meanings: `(동물) horse`, `(마지막) end (of), close (of)`

[http://endic.naver.com/search.nhn?sLn=kr&dicQuery=%EB%A7%90&x=0&y=0&query=%EB%A7%90&target=endic&ie=utf8&query_utf=&isOnlyViewEE=N](http://endic.naver.com/search.nhn?sLn=kr&dicQuery=%EB%A7%90&x=0&y=0&query=%EB%A7%90&target=endic&ie=utf8&query_utf=&isOnlyViewEE=N)

I think additional options is necessary to select another meanings.(Default is the first meaning)
ex) `ndic.search('blablabla', number=2)` or `$ ndic  아무말 --number 2` in shell scripts => the second meaning

**Comment by jupiny** [comment]
Please refer to http://ndic.readthedocs.io/en/latest/#multiple-definitions
